### ISSUE TITLE
After creating a new print format using dialog

### ISSUE THREAD

**Issue by NagariaHussain** [frappe/print_designer#119]
![CleanShot 2023-12-31 at 16 16 45@2x](https://github.com/frappe/print_designer/assets/34810212/daabebba-880b-44d8-b485-b24e34d71bdc)

### App Versions
```
{
	"frappe": "16.0.0-dev",
	"print_designer": "1.0.0",
	"raven": "1.3.2",
	"tldraw_whiteboard": "0.0.1"
}
```
### Route
```
print-designer/Service Invoice
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1680, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
TypeError: get_data_from_main_template() missing 1 required positional argument: 'docname'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"string": "",
		"doctype": "Invoice",
		"settings": "{}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/print_designer.print_designer.page.print_designer.print_designer.get_data_from_main_template",
	"request_id": "53c01a1d-6272-4406-9b9e-690cdc15b278"
}
```
### Response Data
```
{
	"exception": "TypeError: get_data_from_main_template() missing 1 required positional argument: 'docname'",
	"exc_type": "TypeError"
}
```

**Comment by maharshivpatel** [comment]
@NagariaHussain will fix this but refresh and it should work for now.

**Comment by maharshivpatel** [comment]
fixed by #120
