### ISSUE TITLE
Installation Error - Problems During Build

### ISSUE THREAD

**Issue by zerodiscount** [frappe/print_designer#138]
Unable to install app. Frappe version - 15.10.0. Nodejs version 18.8 (installed via snap).

Get the followinng error when attempting installation with command ` bench get-app https://github.com/frappe/print_designer --resolve-deps` . Also opened issue on forum: 
https://discuss.frappe.io/t/introducing-print-designer-a-brand-new-way-of-designing-print-formats/106280/35?u=zerodiscount

`ERROR  There were some problems during build

Error: Build failed with 407 errors:
../print_designer/print_designer/public/js/print_designer/composables/AttachKeyBindings.js:1:9: ERROR: No matching export in "../../node_modules/vue/dist/vue.runtime.esm.js" for import "onMounted"
../print_designer/print_designer/public/js/print_designer/composables/AttachKeyBindings.js:1:20: ERROR: No matching export in "../../node_modules/vue/dist/vue.runtime.esm.js" for import "onUnmounted"
../print_designer/print_designer/public/js/print_designer/composables/Draw.js:1:9: ERROR: No matching export in "../../node_modules/vue/dist/vue.runtime.esm.js" for import "reactive"
../print_designer/print_designer/public/js/print_designer/composables/Element.js:6:9: ERROR: No matching export in "../../node_modules/vue/dist/vue.runtime.esm.js" for import "watch"
../print_designer/print_designer/public/js/print_designer/composables/Element.js:6:16: ERROR: No matching export in "../../node_modules/vue/dist/vue.runtime.esm.js" for import "markRaw"
...
    at failureErrorWithLog (/home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:1624:15)
    at /home/frappe/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:1266:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Terminated
error Command failed with exit code 143.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Traceback

`Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py", line 72, in build
    bundle(
  File "/home/frappe/frappe-bench/apps/frappe/frappe/build.py", line 257, in bundle
    frappe.commands.popen(command, cwd=frappe_app_path, env=get_node_env(), raise_err=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 97, in popen
    raise subprocess.CalledProcessError(return_, command)
subprocess.CalledProcessError: Command 'yarn run production --apps print_designer --run-build-command' returned non-zero exit status 143.
ERROR: bench build --app print_designer
subprocess.CalledProcessError: Command 'bench build --app print_designer' returned non-zero exit status 1.`

**Comment by maharshivpatel** [comment]
@zerodiscount can you please try  running following commands

```
bench setup requirements
```
```
bench build
```

**Comment by zerodiscount** [comment]
Bench setup requirements works fine for all apps (including frappe, erpnext, gameplan, builder and for this app) but bench build fails when this app is installed. Bench build works fine when this app has been removed.

Dont know if relevant but I do see the following  warning when I try to run bench build with this app:

```
[3/4] Linking dependencies...
warning " > @interactjs/actions@1.10.17" has unmet peer dependency "@interactjs/core@1.10.17".
warning " > @interactjs/actions@1.10.17" has unmet peer dependency "@interactjs/utils@1.10.17".
warning " > @interactjs/auto-start@1.10.17" has unmet peer dependency "@interactjs/core@1.10.17".
warning " > @interactjs/auto-start@1.10.17" has unmet peer dependency "@interactjs/utils@1.10.17".
warning " > @interactjs/modifiers@1.10.17" has unmet peer dependency "@interactjs/core@1.10.17".
warning " > @interactjs/modifiers@1.10.17" has unmet peer dependency "@interactjs/utils@1.10.17".
warning "@interactjs/modifiers > @interactjs/snappers@1.10.17" has unmet peer dependency "@interactjs/utils@1.10.17".
```

**Comment by maharshivpatel** [comment]
@zerodiscount closing, this is most likely local setup issue and not related to print designer. please create new bench and try on new fresh site. thank you
