### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by classita** [frappe/print_designer#207]
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @interactjs/actions@1.10.17" has unmet peer dependency "@interactjs/core@1.10.17".
warning " > @interactjs/actions@1.10.17" has unmet peer dependency "@interactjs/utils@1.10.17".
warning " > @interactjs/auto-start@1.10.17" has unmet peer dependency "@interactjs/core@1.10.17".
warning " > @interactjs/auto-start@1.10.17" has unmet peer dependency "@interactjs/utils@1.10.17".
warning " > @interactjs/modifiers@1.10.17" has unmet peer dependency "@interactjs/core@1.10.17".
warning " > @interactjs/modifiers@1.10.17" has unmet peer dependency "@interactjs/utils@1.10.17".
warning "@interactjs/modifiers > @interactjs/snappers@1.10.17" has unmet peer dependency "@interactjs/utils@1.10.17".
[4/4] Building fresh packages...
Done in 12.73s.
$ bench build --app print_designer
Traceback (most recent call last):
  File "/home/user/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 75, in get_app_commands
    app_command_module = importlib.import_module(f"{app}.commands")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fullsize'
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/user/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/user/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/user/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/home/user/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/frappe-bench/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/user/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 44, in app_group
    ctx.obj = {"sites": get_sites(site), "force": force, "verbose": verbose, "profile": profile}
  File "/home/user/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 56, in get_sites
    elif default_site := frappe.get_conf().default_site:
  File "/home/user/frappe-bench/apps/frappe/frappe/__init__.py", line 385, in get_conf
    with init_site(site):
  File "/home/user/frappe-bench/apps/frappe/frappe/__init__.py", line 395, in __enter__
    init(self.site)
  File "/home/user/frappe-bench/apps/frappe/frappe/__init__.py", line 259, in init
    setup_module_map()
  File "/home/user/frappe-bench/apps/frappe/frappe/__init__.py", line 1613, in setup_module_map
    for module in get_module_list(app):
  File "/home/user/frappe-bench/apps/frappe/frappe/__init__.py", line 1472, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/user/frappe-bench/apps/frappe/frappe/__init__.py", line 1437, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/user/frappe-bench/apps/frappe/frappe/__init__.py", line 1467, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/user/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fullsize'
ERROR: bench build --app print_designer
subprocess.CalledProcessError: Command 'bench build --app print_designer' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/user/.local/lib/python3.10/site-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/home/user/.local/lib/python3.10/site-packages/bench/commands/make.py", line 181, in get_app
    get_app(
  File "/home/user/.local/lib/python3.10/site-packages/bench/app.py", line 772, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/home/user/.local/lib/python3.10/site-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/bench/app.py", line 255, in install
    install_app(
  File "/home/user/.local/lib/python3.10/site-packages/bench/app.py", line 920, in install_app
    build_assets(bench_path=bench_path, app=app, using_cached=using_cached)
  File "/home/user/.local/lib/python3.10/site-packages/bench/utils/bench.py", line 380, in build_assets
    exec_cmd(command, cwd=bench_path, env=env)
  File "/home/user/.local/lib/python3.10/site-packages/bench/utils/__init__.py", line 169, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: bench build --app print_designer

**Comment by maharshivpatel** [comment]
@classita this looks like a setup issue, not sure if this is specific to print_designer.  please share more details if you think this is caused by print_designer
