### ISSUE TITLE
Unable to Generate or Preview Invoices - Page Stuck in Loading Stat

### ISSUE THREAD

**Issue by Venkateshvenki404224** [frappe/print_designer#384]
I am facing an issue while generating and previewing invoices in Frappe. Whenever I try to generate an invoice that is designed using print designer or access the preview, the page enters a loading state and eventually shows an error. However, the error logs do not display any related information, making it difficult to debug the issue.

https://github.com/user-attachments/assets/5c9f6c64-80e5-48e8-b57b-77c6a3c2cb14

![image_2024-12-27_11-32-00](https://github.com/user-attachments/assets/795bed70-ec8d-4baf-acae-d6d136ec8629)

![image](https://github.com/user-attachments/assets/c4657cc0-22e3-46c6-a11f-c76fc5efff52)

I am using Print Designer Version:
```
print_designer 1.2.0
```
I would appreciate any guidance on how to troubleshoot or resolve this issue. Is there a way to enable more detailed logging to capture what’s going wrong? Or are there known issues or fixes for this behavior in the current version?

Thank you for your support!

**Comment by RaySolo** [comment]
I get the same error message. The LOG says that I cannot access the .jpg because it does not exist. but that is not true. the file exists, the user and access rights are also correct. 

Traceback with variables (most recent call last):
  File "apps/frappe/frappe/core/doctype/file/utils.py", line 372, in attach_files_to_document
    file.insert(ignore_permissions=True)
      doc = <PDPrintFormat: PD SalesOrder V143.1>
      event = 'on_update'
      attach_fields = [<Attach ImageDocField: print_designer_preview_img parent=Print Format>]
      df = <Attach ImageDocField: print_designer_preview_img parent=Print Format>
      value = '/private/files/print_designer-pd_salesorder_v143.1-preview.jpg'
      unattached_file = None
      file = <File: unsaved>
  File "apps/frappe/frappe/model/document.py", line 289, in insert
    self.run_method("before_insert")
      self = <File: unsaved>
      ignore_permissions = True
      ignore_links = None
      ignore_if_duplicate = False
      ignore_mandatory = None
      set_name = None
      set_child_names = True
  File "apps/frappe/frappe/model/document.py", line 974, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
      self = <File: unsaved>
      method = 'before_insert'
      args = ()
      kwargs = {}
      fn = <function Document.run_method.<locals>.fn at 0x79fbf6359d00>
  File "apps/frappe/frappe/model/document.py", line 1334, in composer
    return composed(self, method, *args, **kwargs)
      self = <File: unsaved>
      args = ()
      kwargs = {}
      hooks = []
      method = 'before_insert'
      doc_events = {'*': {'on_update': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.core.doctype.file.utils.attach_files_to_document', 'frappe.automation.doctype.assignment_rule.assignment_rule.apply', 'frappe.automation.doctype.assignment_rule.assignment_rule.update_due_date', 'frappe.core.doctype.user_type.user_type.apply_permissions_for_non_standard_user_type'], 'after_rename': ['frappe.desk.notifications.clear_doctype_notifications'], 'on_cancel': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.automation.doctype.assignment_rule.assignment_rule.apply'], 'on_trash': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions'], 'on_update_after_submit': ['frappe.workflow.doctype.workflow_action.workflow_action.process_w...
      composed = <function Document.hook.<locals>.compose.<locals>.runner at 0x79fbf6359940>
      compose = <function Document.hook.<locals>.compose at 0x79fbf6358f40>
      f = <function Document.run_method.<locals>.fn at 0x79fbf6359d00>
  File "apps/frappe/frappe/model/document.py", line 1316, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
      self = <File: unsaved>
      method = 'before_insert'
      args = ()
      kwargs = {}
      add_to_return_value = <function Document.hook.<locals>.add_to_return_value at 0x79fbf6359da0>
      fn = <function Document.run_method.<locals>.fn at 0x79fbf6359d00>
      hooks = ()
  File "apps/frappe/frappe/model/document.py", line 971, in fn
    return method_object(*args, **kwargs)
      self = <File: unsaved>
      args = ()
      kwargs = {}
      method_object = <bound method File.before_insert of <File: unsaved>>
      method = 'before_insert'
  File "apps/frappe/frappe/core/doctype/file/file.py", line 104, in before_insert
    self.save_file(content=self.get_content())
      self = <File: unsaved>
  File "apps/frappe/frappe/core/doctype/file/file.py", line 539, in get_content
    with open(file_path, mode="rb") as f:
      self = <File: unsaved>
      file_path = './erpdev.lan/private/files/print_designer-pd_salesorder_v143.1-preview.jpg'
builtins.FileNotFoundError: [Errno 2] No such file or directory: './erpdev.lan/private/files/print_designer-pd_salesorder_v143.1-preview.jpg'

**Comment by MiDOZ** [comment]
I have got the same issue, the file does not exist for me tho, here is the stack trace:
`Traceback with variables (most recent call last):
  File "apps/frappe/frappe/core/doctype/file/utils.py", line 372, in attach_files_to_document
    file.insert(ignore_permissions=True)
      doc = <PDPrintFormat: Sales Order PD v2>
      event = 'on_update'
      attach_fields = [<Attach ImageDocField: print_designer_preview_img parent=Print Format>]
      df = <Attach ImageDocField: print_designer_preview_img parent=Print Format>
      value = '/private/files/print_designer-sales_order_pd_v2-preview3f12d3.jpg'
      unattached_file = None
      file = <File: unsaved>
  File "apps/frappe/frappe/model/document.py", line 289, in insert
    self.run_method("before_insert")
      self = <File: unsaved>
      ignore_permissions = True
      ignore_links = None
      ignore_if_duplicate = False
      ignore_mandatory = None
      set_name = None
      set_child_names = True
  File "apps/frappe/frappe/model/document.py", line 974, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
      self = <File: unsaved>
      method = 'before_insert'
      args = ()
      kwargs = {}
      fn = <function Document.run_method.<locals>.fn at 0x75d9041d59e0>
  File "apps/frappe/frappe/model/document.py", line 1334, in composer
    return composed(self, method, *args, **kwargs)
      self = <File: unsaved>
      args = ()
      kwargs = {}
      hooks = []
      method = 'before_insert'
      doc_events = {'*': {'on_update': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.core.doctype.file.utils.attach_files_to_document', 'frappe.automation.doctype.assignment_rule.assignment_rule.apply', 'frappe.automation.doctype.assignment_rule.assignment_rule.update_due_date', 'frappe.core.doctype.user_type.user_type.apply_permissions_for_non_standard_user_type'], 'after_rename': ['frappe.desk.notifications.clear_doctype_notifications'], 'on_cancel': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions', 'frappe.automation.doctype.assignment_rule.assignment_rule.apply'], 'on_trash': ['frappe.desk.notifications.clear_doctype_notifications', 'frappe.workflow.doctype.workflow_action.workflow_action.process_workflow_actions'], 'on_update_after_submit': ['frappe.workflow.doctype.workflow_action.workflow_action.process_w...
      composed = <function Document.hook.<locals>.compose.<locals>.runner at 0x75d9041d6160>
      compose = <function Document.hook.<locals>.compose at 0x75d9041d5940>
      f = <function Document.run_method.<locals>.fn at 0x75d9041d59e0>
  File "apps/frappe/frappe/model/document.py", line 1316, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
      self = <File: unsaved>
      method = 'before_insert'
      args = ()
      kwargs = {}
      add_to_return_value = <function Document.hook.<locals>.add_to_return_value at 0x75d9041d5bc0>
      fn = <function Document.run_method.<locals>.fn at 0x75d9041d59e0>
      hooks = ()
  File "apps/frappe/frappe/model/document.py", line 971, in fn
    return method_object(*args, **kwargs)
      self = <File: unsaved>
      args = ()
      kwargs = {}
      method_object = <bound method File.before_insert of <File: unsaved>>
      method = 'before_insert'
  File "apps/frappe/frappe/core/doctype/file/file.py", line 104, in before_insert
    self.save_file(content=self.get_content())
      self = <File: unsaved>
  File "apps/frappe/frappe/core/doctype/file/file.py", line 539, in get_content
    with open(file_path, mode="rb") as f:
      self = <File: unsaved>
      file_path = './mtech.local/private/files/print_designer-sales_order_pd_v2-preview3f12d3.jpg'
builtins.FileNotFoundError: [Errno 2] No such file or directory: './mtech.local/private/files/print_designer-sales_order_pd_v2-preview3f12d3.jpg'`

**Comment by vintalie** [comment]
thats is the code snippet:
`def attach_files_to_document(doc: "Document", event) -> None:
	"""Runs on on_update hook of all documents.
	Goes through every file linked with the Attach and Attach Image field and attaches
	the file to the document if not already attached. If no file is found, a new file
	is created.
	"""

	attach_fields = doc.meta.get("fields", {"fieldtype": ["in", ["Attach", "Attach Image"]]})

	for df in attach_fields:
		# this method runs in on_update hook of all documents
		# we dont want the update to fail if file cannot be attached for some reason
		value = doc.get(df.fieldname)
		if not (value or "").startswith(("/files", "/private/files")):
			continue

		if frappe.db.exists(
			"File",
			{
				"file_url": value,
				"attached_to_name": doc.name,
				"attached_to_doctype": doc.doctype,
				"attached_to_field": df.fieldname,
			},
		):
			continue

		unattached_file = frappe.db.exists(
			"File",
			{
				"file_url": value,
				"attached_to_name": None,
				"attached_to_doctype": None,
				"attached_to_field": None,
			},
		)

		if unattached_file:
			frappe.db.set_value(
				"File",
				unattached_file,
				field={
					"attached_to_name": doc.name,
					"attached_to_doctype": doc.doctype,
					"attached_to_field": df.fieldname,
					"is_private": cint(value.startswith("/private")),
				},
			)
			continue

		file: File = frappe.get_doc(
			doctype="File",
			file_url=value,
			attached_to_name=doc.name,
			attached_to_doctype=doc.doctype,
			attached_to_field=df.fieldname,
			folder="Home/Attachments",
		)
		try:
			file.insert(ignore_permissions=True)
		except Exception:
			doc.log_error("Error Attaching File")
`

from = https://github.com/frappe/frappe/blob/develop/frappe/core/doctype/file/utils.py

analyzing this code it seems to me that first it checks if the value received exists, if it is different from an empty string, and does not start with "/files" or "/private/files", then it will check the existence of the file in the db, and if it doesn't exist, it will create a new one. It seems to me that the attacked image is not in the database and the function tries to overwrite it, generating an error.

sorry for the english from the google translator
Can you send me a print of the image folder and the File table in the database?

**Comment by MiDOZ** [comment]
Hello, thank you for your feedback, here are the files:
```
user@erpnext:~/frappe-bench/sites/site.name/private/files$ ls -l
total 16
-rw-r--r-- 1 user user 15820 Jan 13 16:00 500.png
```
`select * from tabFile`

`+------------------+----------------------------+----------------------------+---------------+---------------+-----------+--------+-------------+------------+-----+-------------+------------------------+--------+------------------+-----------+---------------------+------------+-----------+----------------+-----------------------+---------------+--------+-----------+-------------------+------------+----------------------------------+---------------------+--------------------------+------------+-----------+---------+-----------+
| name             | creation                   | modified                   | modified_by   | owner         | docstatus | parent | parentfield | parenttype | idx | file_name   | file_url               | module | attached_to_name | file_size | attached_to_doctype | is_private | file_type | is_home_folder | is_attachments_folder | thumbnail_url | folder | is_folder | attached_to_field | old_parent | content_hash                     | uploaded_to_dropbox | uploaded_to_google_drive | _user_tags | _comments | _assign | _liked_by |
+------------------+----------------------------+----------------------------+---------------+---------------+-----------+--------+-------------+------------+-----+-------------+------------------------+--------+------------------+-----------+---------------------+------------+-----------+----------------+-----------------------+---------------+--------+-----------+-------------------+------------+----------------------------------+---------------------+--------------------------+------------+-----------+---------+-----------+
| 256911c07a       | 2025-01-13 16:00:07.646519 | 2025-01-13 16:00:07.646519 | Administrator | Administrator |         0 | NULL   | NULL        | NULL       |   0 | 500.png     | /private/files/500.png | NULL   | NULL             |     15820 | NULL                |          1 | PNG       |              0 |                     0 | NULL          | Home   |         0 | NULL              | NULL       | 52c4e5e43ce5a02189f15759f176627b |                   0 |
              0 | NULL       | NULL      | NULL    | NULL      |
| Home             | 2025-01-08 20:12:21.570625 | 2025-01-08 20:12:21.570625 | Administrator | Administrator |         0 | NULL   | NULL        | NULL       |   2 | Home        | NULL                   | NULL   | NULL             |         0 | NULL                |          0 | NULL      |              1 |                     0 | NULL          | NULL   |         1 | NULL              | NULL       | NULL                             |                   0 |
              0 | NULL       | NULL      | NULL    | NULL      |
| Home/Attachments | 2025-01-08 20:12:21.579538 | 2025-01-08 20:12:21.579538 | Administrator | Administrator |         0 | NULL   | NULL        | NULL       |   0 | Attachments | NULL                   | NULL   | NULL             |         0 | NULL                |          0 | NULL      |              0 |                     1 | NULL          | Home   |         1 | NULL              | NULL       | NULL                             |                   0 |
              0 | NULL       | NULL      | NULL    | NULL      |
+------------------+----------------------------+----------------------------+---------------+---------------+-----------+--------+-------------+------------+-----+-------------+------------------------+--------+------------------+-----------+---------------------+------------+-----------+----------------+-----------------------+---------------+--------+-----------+-------------------+------------+----------------------------------+---------------------+--------------------------+------------+-----------+---------+-----------+`

**Comment by vintalie** [comment]
The error seems to be simpler than it seems, perhaps Python is unable to access the file's destination url. see that the function first checks if it is a url, after that it uses a function to search for the path (or url) of the file. 

How are your files being served? Do you have a system (eg nginx)? Can you somehow access the image via the url? As you said, this is a clean installation so I'm going to disregard that there is any app permissions setting preventing access.

It will be useful to know how you did the entire process and if you have any configuration to deploy.

![Image](https://github.com/user-attachments/assets/ddc29a26-3a89-450d-bd8c-c079eed2d2d8)

**Comment by MiDOZ** [comment]
It's actually very weird, I have two different sites hosted on two different ports, both in production.
they are `system.com` and `mtech.local`.



![Image](https://github.com/user-attachments/assets/887b367d-ebf0-4e03-a8e1-2a3f7267088b)

![Image](https://github.com/user-attachments/assets/1d675368-fbf0-4614-90fa-b4ef6f3d14df)

System.com - Print designer layout and preview with error on MT-Sales-Invoice
![Image](https://github.com/user-attachments/assets/91f66439-f4ac-4e58-96ab-2a29b7f0282a)
![Image](https://github.com/user-attachments/assets/c6152706-5ae6-4a19-a4dc-0b25e08067aa)

mtech.local designer + preview

![Image](https://github.com/user-attachments/assets/687e664b-3b2a-4397-92e7-016a617d6006)
![Image](https://github.com/user-attachments/assets/9b242d30-41d4-41d6-bf14-2c534f8b9f6a)

original design preview error too
![Image](https://github.com/user-attachments/assets/79a723ea-0301-40aa-8650-e68230ffd90d)

Error when clicking PDF download
![Image](https://github.com/user-attachments/assets/4fbcd4eb-a09f-4644-83dc-7d0a9f906a41)

[mtech.local when clicking on PDF download.txt](https://github.com/user-attachments/files/18441411/mtech.local.when.clicking.on.PDF.download.txt)

[system.com error.txt](https://github.com/user-attachments/files/18441413/system.com.error.txt)

The paths in the db are considering the root folder is the site folder.

**Comment by MiDOZ** [comment]
> [@MiDOZ](https://github.com/MiDOZ) as you can see in the error you have incorrect wkhtmltopdf version. please install correct version using instructions shared in error or in FAQ No 1. https://github.com/frappe/print_designer?tab=readme-ov-file#faq

@maharshivpatel I installed the correct version now, but I'm presented with another error:

`Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 50, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1726, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/print_format.py", line 236, in download_pdf
    pdf_file = frappe.get_print(
               ^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 2142, in get_print
    return get_pdf(html, options=pdf_options, output=output) if as_pdf else html
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/pdf.py", line 90, in get_pdf
    filedata = pdfkit.from_string(html, options=options or {}, verbose=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pdfkit/api.py", line 75, in from_string
    return r.to_pdf(output_path)
           ^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pdfkit/pdfkit.py", line 201, in to_pdf
    self.handle_error(exit_code, stderr)
  File "env/lib/python3.11/site-packages/pdfkit/pdfkit.py", line 155, in handle_error
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
Exit with code 1 due to network error: ConnectionRefusedError`



![Image](https://github.com/user-attachments/assets/6e4fa9e6-a23c-4bc7-97bb-d6c1bd58aeb8)

**Comment by RaySolo** [comment]
To isolate the problem, I replaced the routine get_pdf() within pdf.py, in which wkhtmltopdf is called, with a routine that works with puppeteer. The problem disappeared. The form previously created with print designer could be displayed. 
i fear that many of our problems probably have more to do with wkhtmltopdf than we would like. maybe now is a good time to make the change.
