### ISSUE TITLE
Failed get-app https://github.com/frappe/print_designer

### ISSUE THREAD

**Issue by xhijack** [frappe/print_designer#7]
`yarn run v1.22.19
$ node esbuild --production --apps print_designer --run-build-command
clean: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
✘ [ERROR] Could not resolve "pinia"

    ../print_designer/print_designer/public/js/print_designer/print_designer.bundle.js:2:28:
      2 │ import { createPinia } from "pinia";
        ╵                             ~~~~~~~

  You can mark the path "pinia" as external to exclude it from the bundle, which will remove this
  error.

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
✘ [ERROR] [plugin vue] Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.

1  |  
2  |  <link rel="preconnect" href="https://fonts.gstatic.com" />
   |                                                             
3  |  <link
   |  ^^^^^
4  |    v-for="currentFont in MainStore.currentFonts"
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
5  |    :key="currentFont"
   |  ^^^^^^^^^^^^^^^^^^^
6  |    :href="`https://fonts.googleapis.com/css2?family=${currentFont}:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap`"
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
7  |    rel="stylesheet"
   |  ^^^^^^^^^^^^^^^^^
8  |  />
   |  ^^
9  |  <AppHeader :print_format_name="print_format_name" />
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
10 |  <div class="main-layout" id="main-layout">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11 |    <AppToolbar :class="toolbarClasses" />
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12 |    <AppCanvas class="app-sections print-format-container" />
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13 |    <AppPropertiesPanel class="app-sections properties-panel" />
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14 |  </div>
   |  ^^^^^^

    ../print_designer/print_designer/public/js/print_designer/print_designer.bundle.js:3:21:
      3 │ import Designer from "./App.vue";
        ╵                      ~~~~~~~~~~~

 ERROR  There were some problems during build

Error: Build failed with 2 errors:
../print_designer/print_designer/public/js/print_designer/print_designer.bundle.js:2:28: ERROR: Could not resolve "pinia"
../print_designer/print_designer/public/js/print_designer/print_designer.bundle.js:3:21: ERROR: [plugin: vue] Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.

1  |  
2  |  <link rel="preconnect" href="https://fonts.gstatic.com" />
   |                                                             
3  |  <link
   |  ^^^^^
4  |    v-for="currentFont in MainStore.currentFonts"
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
5  |    :key="currentFont"
   |  ^^^^^^^^^^^^^^^^^^^
6  |    :href="`https://fonts.googleapis.com/css2?family=${currentFont}:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap`"
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
7  |    rel="stylesheet"
   |  ^^^^^^^^^^^^^^^^^
8  |  />
   |  ^^
9  |  <AppHeader :print_format_name="print_format_name" />
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
10 |  <div class="main-layout" id="main-layout">
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11 |    <AppToolbar :class="toolbarClasses" />
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
12 |    <AppCanvas class="app-sections print-format-container" />
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13 |    <AppPropertiesPanel class="app-sections properties-panel" />
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14 |  </div>
   |  ^^^^^^
    at failureErrorWithLog (/opt/bench/erpnext/apps/frappe/node_modules/esbuild/lib/main.js:1600:15)
    at /opt/bench/erpnext/apps/frappe/node_modules/esbuild/lib/main.js:1246:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Terminated
error Command failed with exit code 143.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/opt/bench/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/opt/bench/erpnext/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/bench/erpnext/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/bench/erpnext/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bench/erpnext/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/bench/erpnext/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/bench/erpnext/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/bench/erpnext/apps/frappe/frappe/commands/utils.py", line 86, in build
    bundle(mode, apps=apps, hard_link=hard_link, verbose=verbose, skip_frappe=skip_frappe)
  File "/opt/bench/erpnext/apps/frappe/frappe/build.py", line 257, in bundle
    frappe.commands.popen(command, cwd=frappe_app_path, env=get_node_env(), raise_err=True)
  File "/opt/bench/erpnext/apps/frappe/frappe/commands/__init__.py", line 98, in popen
    raise subprocess.CalledProcessError(return_, command)
subprocess.CalledProcessError: Command 'yarn run production --apps print_designer --run-build-command' returned non-zero exit status 143.
ERROR: 
Traceback (most recent call last):
  File "/home/erpnext/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/opt/bench/bench-repo/bench/cli.py", line 127, in cli
    bench_command()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/bench/bench-repo/bench/commands/make.py", line 159, in get_app
    get_app(
  File "/opt/bench/bench-repo/bench/app.py", line 444, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/opt/bench/bench-repo/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/opt/bench/bench-repo/bench/app.py", line 242, in install
    install_app(
  File "/opt/bench/bench-repo/bench/app.py", line 586, in install_app
    build_assets(bench_path=bench_path, app=app)
  File "/opt/bench/bench-repo/bench/utils/bench.py", line 345, in build_assets
    exec_cmd(command, cwd=bench_path, env={"BENCH_DEVELOPER": "1"})
  File "/opt/bench/bench-repo/bench/utils/__init__.py", line 158, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError`

failed when bench get-app get-app https://github.com/frappe/print_designer

ecommerce_integrations 1.15.4
erpnext 14.15.1
frappe 14.36.0
helpdesk 0.8.3

ubuntu 22.04

**Comment by maharshivpatel** [comment]
Please note that print designer is only compatible with develop version of frappe framework. v14 is not supported as this app requires vue3.
